env:
  rclone_config: "ENCRYPTED[a6cf9923df82b942fd0861a9f8d5d69814a5bd701f18e08ffc74aa58195abbc390a8a99841e6c5b4cc8a3ca7ce5606ae]"
  git_cookies: "ENCRYPTED[89bdabeefcf8861cffd45da07272ac5c2d19ff5e1a71500e0ddeb2645d6d6a872ebd734c7e232be7a9cce66cbf4c1cf7]"
  tg_auth: "ENCRYPTED[db26d62a3a296d65335edd90f1a983bb232a5970c385728092f7a4d984cadf7641f8fbabc321bf9eb128e8960ac1176a]"

container:
  image: fr3akyphantom/droid-builder
  cpu: 8
  memory: 32G

task:
    name: Hyouka Builder
    timeout_in: 120m
    ccachesync_background_script:
      - ./ccachesync
    syncsource_script:
      - ./syncsource
    romcompile_script:
      - ./romcompile
    uploadrom_script:
      - ./uploadrom
