env:
  rclone_config: "ENCRYPTED[a6cf9923df82b942fd0861a9f8d5d69814a5bd701f18e08ffc74aa58195abbc390a8a99841e6c5b4cc8a3ca7ce5606ae]"
  git_cookies: "ENCRYPTED[89bdabeefcf8861cffd45da07272ac5c2d19ff5e1a71500e0ddeb2645d6d6a872ebd734c7e232be7a9cce66cbf4c1cf7]"
  tg_auth: "ENCRYPTED[a24eb8229da13d90b998af3a6b049f49b51aee0bad69c4ef418769e2179f16ab9964f478d8aa893e3cf42607d6b90843]"

container:
  image: fr3akyphantom/droid-builder
  cpu: 8
  memory: 32G

task:
    name: Hyouka Builder
    timeout_in: 120m
    ccachesync_background_script:
      - ./ccachesync
    ssh_background_script:
      - ./tmate.sh
    syncsource_script:
      - ./syncsource
    romcompile_script:
      - ./romcompile
    uploadrom_script:
      - ./uploadrom
