#!/bin/bash
#
# Setup Configs
cd /tmp
mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf
echo "$tg_auth" > ~/.telegram.sh
export CCACHE_DIR=/tmp/ccache

# Pull CCache
rclone copy remote:/ccache/derpccache.tar.gz /tmp -P
tar xf derpccache.tar.gz
rm derpccache.tar.gz

# Tmate session in case of build errors
tmate -S /tmp/tmate.sock new-session -d
tmate -S /tmp/tmate.sock wait tmate-ready
echo "$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')" > ~/.ssh_id

# Build command! j10 for 10 cpu, j8 for 8 cpu, otherwise memeroy will end up even its 24G
# Upload rom zip file if succeed to build! Send notification to tg! And send shell to tg if build fails!

# Let's compile by parts! Coz of ram issue!
# make api-stubs-docs || echo no problem
make hiddenapi-lists-docs || echo no problem
make system-api-stubs-docs || echo no problem
make test-api-stubs-docs || echo no problem

mka derp -j8 || echo no problem

# Push CCache
while true
do
sleep 70m
tar --use-compress-program="pigz -k -1 " -cf derpccache.tar.gz ccache
rclone copy derpccache.tar.gz remote:/ccache
rm derpccache.tar.gz
done

ccache -s | telegram -
