#!/bin/bash
cd $HOME

# Notify In telegram
telegram -M "*Dot OS Compile Status*: \`STARTED!\`.
*Started at*:- \`$(date)\`."

# Setup CCache
ccache -M 10G
ccache -z

# Run build process
build_start=$(date +"%s")
#
#
source build/envsetup.sh
lunch dot_daisy-userdebug
make bacon -j8
#
#
build_end=$(date +"%s")
echo "$((build_end - build_start))" > ~/.build_time
