#!/bin/bash
#
cd $HOME

# Configure Git
git config --global color.ui true
git config --global user.name ZunayedDihan
git config --global user.email zunayeddihan@gmail.com

# Git Haxxx xD
echo "${git_cookies}" > ~/git_hax.sh
bash ~/git_hax.sh && rm ~/git_hax.sh

# Repo init and sync
repo init -u https://github.com/AICP/platform_manifest.git -b r11.1 --depth=1 --no-repo-verify -g default,-device,-mips,-darwin,-notdefault
git clone https://github.com/Hotorou/local.git --depth 1 -b master .repo/local_manifests

# Start repo sync
repo sync -j `nproc`

# Purge repo
#rm -rf .repo
